### PR TITLE
remove after hour when undefined

### PR DESCRIPTION
**Pull request by kchiang3**

### CODE REVIEW

**Review by dlee90 — APPROVED** [review]
Looks good.  Although, I would recommend committing format changes and logic changes in different changesets.

**Review by UIApplicationMain — COMMENTED** [review]
delete

**Review by UIApplicationMain — CHANGES_REQUESTED** [review]
Please change the typeof check to
afterLast !== null
since we are really checking for null-ness

**Comment by kchiang3** [comment]
Apparently undefined is different then null in this case. Can you save a
Jason for doe to references?

**Comment by UIApplicationMain** [comment]
Correct, but we are trying to check for null-ness and not undefined type.  We really should be checking if the data is there, hence null!

**Comment by kchiang3** [comment]
Ah, I don't know how the data is strucutred when the day goes on... Does
the parameter just not exist?

**Comment by UIApplicationMain** [comment]
I think it's straight up null in the response? But I'd have to check during hours. @dlee90 tested it and it was good to go.

**Comment by kchiang3** [comment]
pulled request changed

**Review by UIApplicationMain — APPROVED** [review]

**Pull request merged**
